### ISSUE TITLE
bots crashes on 2fort

### ISSUE THREAD

**Issue by Thyraxis** [rosne-gamingyt/cathook#2]
yeah it just crashes again some reason.
no explaination try it for yourself

**Comment by rosne-gamingyt** [comment]
Let me check that out, do you know where in the map it crashes?

**Comment by Thyraxis** [comment]
when it tries to capture the intel or randomly crashes on 2fort

**Comment by rosne-gamingyt** [comment]
Config?

**Comment by rosne-gamingyt** [comment]
Issue resolved.
